<?php
/**
 * AccessTokenApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  PMCore/Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PMCore/Client\Test\Api;

use \PMCore/Client\Configuration;
use \PMCore/Client\ApiException;
use \PMCore/Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AccessTokenApiTest Class Doc Comment
 *
 * @category Class
 * @package  PMCore/Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AccessTokenApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for accessTokenDelete
     *
     * 删除令牌.
     *
     */
    public function testAccessTokenDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for accessTokenPost
     *
     * 创建令牌.
     *
     */
    public function testAccessTokenPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for accessTokenPut
     *
     * 更新令牌.
     *
     */
    public function testAccessTokenPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for accessTokens
     *
     * 令牌列表.
     *
     */
    public function testAccessTokens()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
